# Generated by Django 3.1.1 on 2020-09-17 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_vehicle_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='brand_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=20)),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.vehicle_tb')),
            ],
        ),
    ]
