# Generated by Django 3.1.1 on 2020-10-13 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_state_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='district_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=30)),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.state_tb')),
            ],
        ),
    ]
