# Generated by Django 3.1.1 on 2020-10-20 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_district_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='part_category_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.vehicle_tb')),
            ],
        ),
    ]
