# Generated by Django 3.1.1 on 2021-01-01 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0030_auto_20201213_1843'),
        ('Admin', '0010_reply_tb_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply_tb',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='User.user_tb'),
        ),
    ]
