# Generated by Django 3.1.1 on 2021-03-29 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_reply_tb_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district_tb',
            name='state_id',
        ),
    ]
