# Generated by Django 3.1.1 on 2020-10-13 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_district_tb'),
        ('Workshop', '0002_service_tb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshop_tb',
            old_name='city',
            new_name='place',
        ),
        migrations.AddField(
            model_name='workshop_tb',
            name='country_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='Admin.country_tb'),
        ),
        migrations.AddField(
            model_name='workshop_tb',
            name='district_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='Admin.district_tb'),
        ),
        migrations.AddField(
            model_name='workshop_tb',
            name='state_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='Admin.state_tb'),
        ),
    ]
