# Generated by Django 3.1.1 on 2020-10-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workshop', '0003_auto_20201013_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop_tb',
            name='proof',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
