# Generated by Django 3.1.1 on 2020-10-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workshop', '0004_workshop_tb_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop_tb',
            name='proof',
            field=models.FileField(default='none', max_length=20, upload_to=''),
        ),
    ]
