# Generated by Django 3.1.1 on 2021-01-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workshop', '0005_auto_20201014_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_tb',
            name='service_img',
            field=models.FileField(default='no pic', upload_to=''),
        ),
    ]
