# Generated by Django 3.1.1 on 2021-03-29 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Workshop', '0006_service_tb_service_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop_tb',
            name='country_id',
        ),
        migrations.RemoveField(
            model_name='workshop_tb',
            name='state_id',
        ),
    ]
