# Generated by Django 3.1.1 on 2020-09-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spare_Parts_Shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_tb',
            name='logo',
            field=models.FileField(max_length=50, upload_to=''),
        ),
    ]
