# Generated by Django 3.1.1 on 2020-09-17 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Spare_Parts_Shop', '0002_auto_20200918_0038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop_tb',
            old_name='Address',
            new_name='address',
        ),
    ]
