# Generated by Django 3.1.1 on 2020-09-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spare_Parts_Shop', '0003_auto_20200918_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_tb',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
