# Generated by Django 3.1.1 on 2020-09-18 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_model_tb'),
        ('Spare_Parts_Shop', '0004_shop_tb_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='spare_part_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FileField(max_length=50, upload_to='')),
                ('part_name', models.CharField(max_length=20)),
                ('details', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=20)),
                ('stock', models.CharField(max_length=20)),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.brand_tb')),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.model_tb')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.vehicle_tb')),
            ],
        ),
    ]
