# Generated by Django 3.1.1 on 2020-09-18 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Spare_Parts_Shop', '0005_spare_part_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='spare_part_tb',
            name='shop_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='Spare_Parts_Shop.shop_tb'),
        ),
    ]
