# Generated by Django 3.1.1 on 2020-09-30 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_payment_tb_shop_id'),
        ('Spare_Parts_Shop', '0006_spare_part_tb_shop_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='tracking_details_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_details', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=20)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.order_tb')),
            ],
        ),
    ]
