# Generated by Django 3.1.1 on 2020-09-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spare_Parts_Shop', '0007_tracking_details_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking_details_tb',
            name='time',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
