# Generated by Django 3.1.1 on 2020-10-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spare_Parts_Shop', '0009_auto_20201013_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_tb',
            name='proof',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
