# Generated by Django 3.1.1 on 2020-10-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spare_Parts_Shop', '0010_shop_tb_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_tb',
            name='proof',
            field=models.FileField(default='none', max_length=50, upload_to=''),
        ),
    ]
