# Generated by Django 3.1.1 on 2020-10-20 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_part_category_tb'),
        ('Spare_Parts_Shop', '0011_auto_20201014_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='spare_part_tb',
            name='category_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='Admin.part_category_tb'),
        ),
    ]
