# Generated by Django 3.1.1 on 2021-03-29 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Spare_Parts_Shop', '0012_spare_part_tb_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop_tb',
            name='country_id',
        ),
        migrations.RemoveField(
            model_name='shop_tb',
            name='state_id',
        ),
    ]
