# Generated by Django 3.1.1 on 2020-09-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_tb',
            name='email',
            field=models.CharField(default='email', max_length=20),
        ),
        migrations.AddField(
            model_name='user_tb',
            name='phone',
            field=models.CharField(default='phone', max_length=20),
        ),
    ]
