# Generated by Django 3.1.1 on 2020-09-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_order_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_tb',
            name='date',
            field=models.CharField(default='empty', max_length=20),
        ),
    ]
