# Generated by Django 3.1.1 on 2020-09-25 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Spare_Parts_Shop', '0006_spare_part_tb_shop_id'),
        ('User', '0007_auto_20200925_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_tb',
            name='shop_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='Spare_Parts_Shop.shop_tb'),
        ),
        migrations.AlterField(
            model_name='order_tb',
            name='shop_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='Spare_Parts_Shop.shop_tb'),
        ),
    ]
