# Generated by Django 3.1.1 on 2020-09-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_auto_20200925_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='bank_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_card_number', models.CharField(max_length=20)),
                ('cvv', models.CharField(max_length=20)),
                ('amount', models.CharField(max_length=20)),
            ],
        ),
    ]
