# Generated by Django 3.1.1 on 2020-09-25 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_bank_tb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank_tb',
            old_name='amount',
            new_name='balance',
        ),
        migrations.CreateModel(
            name='payment_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=20)),
                ('transaction_key', models.CharField(max_length=20)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.order_tb')),
            ],
        ),
    ]
