# Generated by Django 3.1.1 on 2020-09-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_auto_20200926_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_tb',
            name='name',
            field=models.CharField(default='nil', max_length=20),
        ),
    ]
