# Generated by Django 3.1.1 on 2020-09-30 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_bank_tb_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_tb',
            name='date',
            field=models.CharField(default='no date', max_length=20),
        ),
        migrations.AddField(
            model_name='payment_tb',
            name='user_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='User.user_tb'),
        ),
    ]
