# Generated by Django 3.1.1 on 2020-10-09 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Workshop', '0002_service_tb'),
        ('User', '0016_complaint_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='workshop_review_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=20)),
                ('review', models.CharField(max_length=500)),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Workshop.workshop_tb')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user_tb')),
            ],
        ),
    ]
