# Generated by Django 3.1.1 on 2020-10-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0017_workshop_review_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating_tb',
            name='date',
            field=models.CharField(default='no date', max_length=20),
        ),
        migrations.AddField(
            model_name='workshop_review_tb',
            name='date',
            field=models.CharField(default='no date', max_length=20),
        ),
    ]
