# Generated by Django 3.1.1 on 2020-10-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0020_prebook_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='prebook_tb',
            name='count',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='prebook_tb',
            name='date',
            field=models.CharField(default='no date', max_length=20),
        ),
    ]
