# Generated by Django 3.1.1 on 2020-10-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0021_auto_20201021_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='prebook_tb',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
