# Generated by Django 3.1.1 on 2020-10-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0022_prebook_tb_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='prebook_tb',
            name='time',
            field=models.CharField(default='no time', max_length=20),
        ),
    ]
