# Generated by Django 3.1.1 on 2020-10-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0023_prebook_tb_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_tb',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
