# Generated by Django 3.1.1 on 2020-12-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0026_notification_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification_tb',
            name='status',
            field=models.CharField(default='unread', max_length=20),
        ),
    ]
