# Generated by Django 3.1.1 on 2020-12-13 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0027_notification_tb_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification_tb',
            name='record_id',
        ),
        migrations.AddField(
            model_name='notification_tb',
            name='order_id',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.order_tb'),
        ),
        migrations.AddField(
            model_name='notification_tb',
            name='prebook_id',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.prebook_tb'),
        ),
    ]
