# Generated by Django 3.1.1 on 2020-12-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0029_auto_20201213_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification_tb',
            name='date',
            field=models.CharField(default='no time', max_length=20),
        ),
        migrations.AddField(
            model_name='notification_tb',
            name='time',
            field=models.CharField(default='no time', max_length=20),
        ),
    ]
