# Generated by Django 3.1.1 on 2021-03-29 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0030_auto_20201213_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_tb',
            name='country_id',
        ),
        migrations.RemoveField(
            model_name='user_tb',
            name='state_id',
        ),
    ]
