# Generated by Django 3.1.1 on 2021-04-06 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0032_order_tb_prebook_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_tb',
            old_name='prebook_status',
            new_name='prebook_id',
        ),
    ]
